#
# Makefile for NKTY DEV drivers
#

obj-$(CONFIG_AT91_HASHTAB) += hashtab.o
#obj-$(CONFIG_NKTYCOMMON) += nktycommon.o
obj-$(CONFIG_AT91_USRI2C_COMMON) += at91_usri2c.o
obj-$(CONFIG_AT91_GPIOB_COMMON) += at91_gpiob.o
obj-$(CONFIG_AT91_SED1335_COMMON) += at91_sed1335.o
obj-$(CONFIG_AT91_DATAFLASH_COMMON) += dataflash.o
obj-$(CONFIG_AT91_FLASH_COMMON) += at91_flash.o

#nktycommon-$(CONFIG_AT91_USRI2C_COMMON) += at91_usri2c.o
#nktycommon-$(CONFIG_AT91_GPIOB_COMMON) += at91_gpiob.o
#nktycommon-$(CONFIG_AT91_SED1335_COMMON) += at91_sed1335.o
#nktycommon-$(CONFIG_AT91_DATAFLASH_COMMON) += dataflash.o
#nktycommon-$(CONFIG_AT91_FLASH_COMMON) += at91_flash.o
#nktycommon-$(CONFIG_AT91_HASHTAB_COMMON) += hashtab.o
