#
# Makefile for NKTY DEV drivers
#

obj-$(CONFIG_AT91_USRI2C) += at91_usri2c.o
obj-$(CONFIG_AT91_GPIOB) += at91_gpiob.o
obj-$(CONFIG_AT91_SED1335) += at91_sed1335.o
obj-$(CONFIG_AT91_DATAFLASH) += dataflash.o
obj-$(CONFIG_AT91_FLASH) += at91_flash.o
